### ISSUE TITLE
:heavy_plus_sign: install micromamba with some softwares

### ISSUE THREAD

**Issue by bunop** [bunop/docker-dorado#1]
Install micromamba with this environment file (or similar):

```yaml
name: ont-dorado
channels:
    - nanoporetech
    - conda-forge
    - bioconda
dependencies:
    - python==3.10
    - samtools>=1.18
    - minimap2==2.28
    - pip:
        - pod5==0.3.2
        - numpy<2.0.0
 ```
